version: '3.8'
services:
  app:
    environment:
      - STATIC_IP=${STATIC_IP}
      - PORT=${PORT}
    build: .
    ports:
      - "${STATIC_IP}:${PORT}:${PORT}"
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    networks:
      - app-network
    command: npm start
networks:
  app-network:
    driver: bridge